version: '3.7'
services:
  redis:
    image: redis:alpine
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - database_data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
    ports:
      - 8080:3000
    depends_on:
      - db
      - redis
  web:
    build:
      context: .
    ports:
      - 3000:80

volumes:
  database_data:
    driver: local